import argparse
import getpass
import os
import time
import shutil
import tempfile
import uuid
from pathlib import Path

from innout import crypto, sources, splitter, stream, unpack, uploader


def get_passphrase(args_passphrase: str | None) -> str:
    if args_passphrase:
        return args_passphrase
    env_pass = os.environ.get("INNOUT_PASSPHRASE")
    if env_pass:
        return env_pass
    return getpass.getpass("Passphrase: ")


def _pick_source(args: argparse.Namespace) -> tuple[str, str]:
    if args.url:
        return "url", args.url
    if args.local:
        return "local", args.local
    if args.github:
        return "github", args.github
    if args.hf:
        return "hf", args.hf
    raise ValueError("One of --url, --local, --github, or --hf must be provided")


def _is_directory_source(source_type: str, source: str) -> bool:
    """True when the source is a tree the streaming pipeline can tar.

    A URL fetches a single file and a --local path may be one; there is
    nothing to walk in either case.
    """
    if source_type in ("hf", "github"):
        return True
    if source_type == "local":
        return Path(source).expanduser().is_dir()
    return False


def _fmt_bytes(n: int) -> str:
    for unit, scale in (("GiB", 1024 ** 3), ("MiB", 1024 ** 2), ("KiB", 1024)):
        if n >= scale:
            return f"{n / scale:.2f} {unit}"
    return f"{n} B"


def cmd_stream_push(
    args: argparse.Namespace, source_type: str, source: str
) -> None:
    """Push a directory source to Drive as encrypted parts, in one pass.

    The source is tarred, encrypted, and split straight into upload-sized
    parts without any stage touching disk at full size, so a 105 GB
    dataset needs about 107 GB free instead of 420 GB.

    Resume is driven by what Drive actually holds, not by trusting the
    local state file: the recorded salt and nonce let the cipher stream be
    regenerated byte-for-byte, and any part already present at the
    recorded size is hashed but neither written nor re-uploaded.
    """
    from innout import drive

    part_size = stream.parse_size(args.part_size)
    suffix = getattr(args, "part_suffix", None) or ""
    passphrase = get_passphrase(args.passphrase)

    work_dir = Path(args.work_dir).expanduser() if args.work_dir else Path(tempfile.mkdtemp())
    work_dir.mkdir(parents=True, exist_ok=True)

    print(f"Acquiring {source} into {work_dir} ...")
    src_dir = sources.acquire_dir(source_type, source, work_dir, repo_type=args.repo_type)
    prefix = args.part_prefix or src_dir.name

    source_bytes = sum(f.stat().st_size for f in src_dir.rglob("*") if f.is_file())
    expected_parts = max(1, -(-source_bytes // part_size))
    print(
        f"Source: {src_dir}  {_fmt_bytes(source_bytes)}  "
        f"-> ~{expected_parts} parts of {_fmt_bytes(part_size)}"
    )
    if suffix:
        print(
            f"Parts will be named {stream.part_name(prefix, 0, suffix)}, ... "
            "-- a cosmetic suffix, not a second layer of protection."
        )

    state_path = work_dir / f"{prefix}.push-state.json"
    state = stream.load_state(state_path)
    if state and (
        state.get("part_size") != part_size
        or state.get("prefix") != prefix
        or state.get("suffix", "") != suffix
    ):
        print(
            "Part size, prefix or suffix changed since the last run; "
            "starting a fresh stream."
        )
        state = {}

    if state.get("salt"):
        salt = bytes.fromhex(state["salt"])
        nonce = bytes.fromhex(state["nonce"])
    else:
        salt, nonce = os.urandom(16), os.urandom(12)

    recorded: dict[str, dict] = dict(state.get("parts") or {})

    def _save() -> None:
        stream.save_state(state_path, {
            "prefix": prefix,
            "part_size": part_size,
            "suffix": suffix,
            "salt": salt.hex(),
            "nonce": nonce.hex(),
            "source": source,
            "parts": recorded,
        })

    _save()  # salt and nonce must survive a crash before the first part lands

    service, folder_id = drive.open_folder(args.drive, args.credentials)
    remote = drive.folder_contents(service, folder_id)
    skip = {
        int(i) for i, info in recorded.items()
        if remote.get(info["name"], {}).get("size") == info["size"]
    }
    if skip:
        print(f"Resuming: {len(skip)} part(s) already in Drive at the recorded size.")

    parts_dir = work_dir / "parts"
    uploaded = 0
    started = time.monotonic()

    def on_part(info: stream.PartInfo) -> None:
        nonlocal uploaded, started
        if info.path is None:
            return  # skipped on resume; the cipher stream still ran through it
        existing = remote.get(info.name)
        drive.upload_one(
            service, folder_id, info.path, info.name,
            replace_id=existing["id"] if existing else None,
        )
        uploaded += 1
        recorded[str(info.index)] = {
            "name": info.name, "size": info.size, "sha256": info.sha256,
        }
        _save()
        done = info.index + 1
        rate = info.size / max(time.monotonic() - started, 1e-9)
        print(
            f"[{done:3d}/~{expected_parts}] {info.name}  {_fmt_bytes(info.size)}  "
            f"sha256={info.sha256[:12]}  {rate / 1e6:.2f} MB/s",
            flush=True,
        )
        started = time.monotonic()

    with stream.tar_stream(src_dir, excludes=args.exclude) as reader:
        result = stream.encrypt_to_parts(
            reader, passphrase, parts_dir, prefix, part_size,
            suffix=suffix, salt=salt, nonce=nonce,
            on_part=on_part, skip_indices=skip,
        )

    expected_total = crypto.HEADER_SIZE + result.plaintext_bytes + crypto.TAG_SIZE
    if result.total_bytes != expected_total:
        raise SystemExit(
            f"error: parts total {result.total_bytes} bytes but the stream "
            f"should be {expected_total}; refusing to publish a manifest"
        )

    # The manifest wears the same suffix as the parts: a bare
    # MANIFEST.sha256 sitting beside 55 .pdf files gives the game away.
    manifest_name = f"MANIFEST.sha256{suffix}"
    manifest = stream.write_manifest(result.parts, work_dir / manifest_name)
    drive.upload_one(
        service, folder_id, manifest, manifest_name,
        replace_id=(remote.get(manifest_name) or {}).get("id"),
    )

    print(
        f"\nDone. {len(result.parts)} part(s), {_fmt_bytes(result.total_bytes)} total, "
        f"{uploaded} uploaded this run."
    )
    print(f"Drive folder: {drive.folder_url(folder_id)}")
    print(f"Manifest: MANIFEST.sha256 (also uploaded)")
    print(f"Pull with: innout pull --from-dir <dir with the parts> --output <dest>")


def cmd_push(args: argparse.Namespace) -> None:
    if not args.server and not args.drive:
        raise SystemExit("error: one of --server or --drive is required")

    source_type, source = _pick_source(args)

    # A directory going to Drive always streams: it needs a quarter of the
    # disk and has no size ceiling, so there is no reason to opt in.
    # --part-size only picks how big each resulting file is. The old
    # four-stage path still handles single files and the --server
    # destination, neither of which has a tree to tar on the fly.
    if args.drive and _is_directory_source(source_type, source):
        return cmd_stream_push(args, source_type, source)

    passphrase = get_passphrase(args.passphrase)
    chunk_size_bytes = args.chunk_size * 1024 * 1024

    tmpdir = tempfile.mkdtemp()
    try:
        src_path = sources.acquire(
            source_type,
            source,
            Path(tmpdir),
            excludes=args.exclude,
            repo_type=args.repo_type,
        )
        session_id = str(uuid.uuid4())
        crypto.encrypt_stream(src_path, Path(tmpdir) / "encrypted", passphrase)
        chunks = splitter.split_file(Path(tmpdir) / "encrypted", session_id, Path(tmpdir), chunk_size_bytes)
        if args.drive:
            from innout import drive

            folder_url = drive.upload_to_drive(chunks, args.drive, args.credentials)
            print(f"Done. Session ID: {session_id}  Parts: {len(chunks)}")
            print(f"Drive folder: {folder_url}")
        else:
            try:
                uploader.upload_chunks(chunks, args.server, session_id, api_key=args.api_key)
            except uploader.MissingAPIKeyError as exc:
                raise SystemExit(str(exc)) from exc
            print(f"Done. Session ID: {session_id}  Parts: {len(chunks)}")
    finally:
        shutil.rmtree(tmpdir, ignore_errors=True)


def _decrypt_and_finalize(tmpdir: Path, output_dir: Path, passphrase: str) -> None:
    """Decrypt the joined blob and emit the friendliest output file.

    Directories arrive as tar.gz; finalize_output decompresses once so the
    user gets `<name>.tar` (single extraction on Windows and Linux) instead
    of an opaque `result` file.
    """
    crypto.decrypt_stream(tmpdir / "encrypted", tmpdir / "decrypted", passphrase)
    final = unpack.finalize_output(tmpdir / "decrypted", output_dir)
    print(f"Done. Output: {final}")
    if final.suffix == ".tar":
        print(f'Extract with: tar -xf "{final.name}"')


def _pull_from_dir(
    args: argparse.Namespace, output_dir: Path, passphrase: str
) -> None:
    """Restore from manually downloaded parts, streaming the whole way.

    The old path joined the parts into one blob, decrypted that to a
    second blob, then moved it -- three full-size copies to restore one
    archive. This decrypts the parts in order straight into the output,
    so the only full-size thing on disk is the result.

    --extract untars on the fly as well, which is the difference between
    needing 105 GB and 210 GB to restore Video-MME-v2.
    """
    from_dir = Path(args.from_dir)
    try:
        parts = stream.find_parts(
            from_dir,
            getattr(args, "part_prefix", None),
            getattr(args, "part_suffix", None),
        )
    except ValueError as exc:
        raise SystemExit(f"error: {exc}") from exc

    # Recover prefix and camouflage suffix from the names rather than
    # making the operator remember what the push was disguised as.
    match = stream.PART_RE.match(parts[0].name)
    prefix, suffix = match["prefix"], match["suffix"]
    total = sum(p.stat().st_size for p in parts)
    print(
        f"{len(parts)} part(s), {_fmt_bytes(total)}, prefix {prefix!r}"
        + (f", suffix {suffix!r}" if suffix else "")
    )

    manifest_path = getattr(args, "manifest", None)
    if manifest_path is None:
        for candidate in (
            from_dir / f"MANIFEST.sha256{suffix}", from_dir / "MANIFEST.sha256"
        ):
            if candidate.exists():
                manifest_path = str(candidate)
                break
    if manifest_path:
        print(f"Verifying parts against {manifest_path} ...")
        try:
            stream.verify_parts(parts, stream.read_manifest(Path(manifest_path)))
        except ValueError as exc:
            raise SystemExit(f"error: {exc}") from exc
        print("All parts match the manifest.")
    else:
        # Worth saying out loud: without a manifest, a corrupt part is only
        # caught by the GCM tag, after the whole output has been written.
        print("No MANIFEST.sha256 found; corruption will only surface at the end.")

    done = [0]

    def on_part(path: Path) -> None:
        done[0] += 1
        print(f"  [{done[0]:3d}/{len(parts)}] {path.name}", flush=True)

    delete_consumed = bool(getattr(args, "delete_consumed", False))
    if delete_consumed:
        print("Parts will be deleted as they are consumed.")

    if getattr(args, "extract", False):
        import tarfile

        with stream.plaintext_stream(
            parts, passphrase,
            delete_consumed=delete_consumed, on_part=on_part,
        ) as reader:
            # "r|*" autodetects compression, so legacy tar.gz pushes extract
            # too, not just the uncompressed tars the streaming push writes.
            with tarfile.open(fileobj=reader, mode="r|*") as tar:
                tar.extractall(output_dir, filter="data")
        print(f"Done. Extracted into: {output_dir}")
        return

    # Stream into a placeholder, then let finalize_output name it after the
    # archive's own top-level directory -- the part prefix is a session UUID
    # for anything pushed before --part-prefix existed, and `<uuid>.tar` is
    # not a name anyone wants. finalize_output also unwraps legacy tar.gz
    # pushes, so both formats land as `<topdir>.tar`.
    blob = output_dir / ".innout-incoming"
    try:
        with open(blob, "wb") as dst:
            for block in stream.iter_plaintext(
                parts, passphrase,
                delete_consumed=delete_consumed, on_part=on_part,
            ):
                dst.write(block)
        final = unpack.finalize_output(blob, output_dir)
    except BaseException:
        blob.unlink(missing_ok=True)
        raise
    print(f"Done. Output: {final}")
    if final.suffix == ".tar":
        print(f'Extract with: tar -xf "{final.name}"')


def cmd_pull(args: argparse.Namespace) -> None:
    output_dir = Path(args.output)
    passphrase = get_passphrase(args.passphrase)
    output_dir.mkdir(parents=True, exist_ok=True)

    if getattr(args, "drive", None):
        from innout import drive
        tmpdir = tempfile.mkdtemp()
        try:
            # A folder may hold several pushes; the positional session id
            # picks one out. Omitted, download_from_drive accepts a
            # single-push folder and refuses an ambiguous one.
            chunks = drive.download_from_drive(
                args.drive, Path(tmpdir), getattr(args, "credentials", None),
                session_id=args.session_id,
            )
            if not chunks:
                raise SystemExit(f"error: no files found in Drive folder {args.drive!r}")
            splitter.join_files(chunks, Path(tmpdir) / "encrypted")
            _decrypt_and_finalize(Path(tmpdir), output_dir, passphrase)
        finally:
            shutil.rmtree(tmpdir, ignore_errors=True)
    elif args.from_dir:
        _pull_from_dir(args, output_dir, passphrase)
    else:
        if not args.session_id:
            raise SystemExit("error: session_id is required when using --server")
        if not args.server:
            raise SystemExit("error: one of --server, --drive, or --from-dir is required")
        tmpdir = tempfile.mkdtemp()
        try:
            try:
                chunks = uploader.download_chunks(
                    args.server, args.session_id, Path(tmpdir), api_key=args.api_key
                )
            except uploader.MissingAPIKeyError as exc:
                raise SystemExit(str(exc)) from exc
            chunks = sorted(chunks, key=lambda p: p.name)
            splitter.join_files(chunks, Path(tmpdir) / "encrypted")
            _decrypt_and_finalize(Path(tmpdir), output_dir, passphrase)
        finally:
            shutil.rmtree(tmpdir, ignore_errors=True)


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        prog="innout",
        description="Encrypt, split, and upload large files/repos to a custom server",
    )
    subparsers = parser.add_subparsers(dest="command", required=True)

    # --- push subcommand ---
    push_parser = subparsers.add_parser("push", help="Upload data to a server or Google Drive")
    source_group = push_parser.add_mutually_exclusive_group(required=True)
    source_group.add_argument("--url", metavar="<url>", help="Remote URL to fetch and push")
    source_group.add_argument("--local", metavar="<path>", help="Local path to push")
    source_group.add_argument("--github", metavar="owner/repo", help="GitHub repo to push")
    source_group.add_argument("--hf", metavar="org/repo", help="HuggingFace repo to push")
    dest_group = push_parser.add_mutually_exclusive_group()
    dest_group.add_argument("--server", metavar="<url>", help="innout server URL")
    dest_group.add_argument(
        "--drive", metavar="<folder>",
        help="Google Drive destination folder; nested paths are created as "
             "needed, e.g. --drive 'VideoMME-v2/videos-001'. Use a separate "
             "folder per push — pull joins every file in the folder",
    )
    push_parser.add_argument(
        "--credentials",
        metavar="<path>",
        default=None,
        help="OAuth client-secrets JSON for Google Drive (default: $INNOUT_CREDENTIALS or ~/.innout_credentials.json)",
    )
    push_parser.add_argument("--passphrase", metavar="<str>", default=None, help="Encryption passphrase")
    push_parser.add_argument(
        "--api-key", metavar="<key>", default=None,
        help="Server API key (overrides INNOUT_API_KEY env var)"
    )
    push_parser.add_argument(
        "--chunk-size",
        metavar="<MB>",
        type=int,
        default=1800,
        help="Chunk size in MB (default: 1800)",
    )
    push_parser.add_argument(
        "--part-size",
        metavar="<size>",
        default="1.8GiB",
        help="Maximum size of each file written to Drive (default: 1.8GiB). "
             "Accepts 1.8GiB, 512MB, or a plain byte count. Applies to "
             "directory sources pushed to --drive, which stream straight "
             "into parts: no stage is written to disk at full size, so a "
             "105 GB source needs ~107 GB free instead of 420 GB",
    )
    push_parser.add_argument(
        "--part-prefix",
        metavar="<name>",
        default=None,
        help="Base name for the parts (default: the source directory name), "
             "giving <prefix>.part000, <prefix>.part001, ...",
    )
    push_parser.add_argument(
        "--part-suffix",
        metavar="<ext>",
        default=None,
        help="Extra suffix appended to every uploaded name, e.g. "
             "--part-suffix .pdf gives <prefix>.part000.pdf. The manifest "
             "takes the same suffix. Purely cosmetic -- the bytes are "
             "AES-256-GCM regardless, and pull recovers the suffix on its own",
    )
    push_parser.add_argument(
        "--work-dir",
        metavar="<path>",
        default=None,
        help="Where to keep the downloaded source and the in-flight part "
             "(default: a temp dir). Reuse the same one to resume a push "
             "without re-downloading the source",
    )
    push_parser.add_argument(
        "--repo-type",
        metavar="<kind>",
        choices=["model", "dataset", "space"],
        default="model",
        help="Kind of HuggingFace repo given to --hf: model, dataset, or space "
             "(default: model). Required for dataset repos, e.g. "
             "--hf MME-Benchmarks/Video-MME-v2 --repo-type dataset",
    )
    push_parser.add_argument(
        "--exclude",
        metavar="<pattern>",
        action="append",
        default=[],
        help="Glob pattern to leave out of directory sources (repeatable), "
             "e.g. --exclude '*.pt' --exclude data",
    )
    push_parser.set_defaults(func=cmd_push)

    # --- pull subcommand ---
    pull_parser = subparsers.add_parser("pull", help="Download and decrypt data")
    pull_parser.add_argument(
        "session_id", metavar="<session_id>", nargs="?", default=None,
        help="Session ID returned by push. Required with --server; with "
             "--drive it selects one push out of a folder holding several",
    )
    source_group_pull = pull_parser.add_mutually_exclusive_group()
    source_group_pull.add_argument("--server", metavar="<url>", help="innout server URL")
    source_group_pull.add_argument(
        "--drive", metavar="<folder>",
        help="Google Drive folder to download from; nested paths supported, "
             "e.g. --drive 'VideoMME-v2/videos-001'",
    )
    source_group_pull.add_argument(
        "--from-dir", metavar="<path>",
        help="Local directory containing manually downloaded chunk files",
    )
    pull_parser.add_argument(
        "--credentials",
        metavar="<path>",
        default=None,
        help="OAuth client-secrets JSON for Google Drive (default: $INNOUT_CREDENTIALS or ~/.innout_credentials.json)",
    )
    pull_parser.add_argument("--passphrase", metavar="<str>", default=None, help="Decryption passphrase")
    pull_parser.add_argument(
        "--api-key", metavar="<key>", default=None,
        help="Server API key (overrides INNOUT_API_KEY env var)"
    )
    pull_parser.add_argument(
        "--output",
        metavar="<dir>",
        default=".",
        help="Output directory (default: current directory)",
    )
    pull_parser.add_argument(
        "--extract",
        action="store_true",
        help="Untar on the fly instead of writing <prefix>.tar, so the "
             "restored tree is the only full-size thing on disk "
             "(105 GB instead of 210 GB for Video-MME-v2). --from-dir only",
    )
    pull_parser.add_argument(
        "--delete-consumed",
        action="store_true",
        help="Delete each part once it has been decrypted. Halves the disk a "
             "restore needs, at the cost of having to re-download a part if "
             "the run fails. --from-dir only",
    )
    pull_parser.add_argument(
        "--manifest",
        metavar="<path>",
        default=None,
        help="sha256 manifest to verify the parts against before decrypting "
             "(default: MANIFEST.sha256 in --from-dir, if present)",
    )
    pull_parser.add_argument(
        "--part-prefix",
        metavar="<name>",
        default=None,
        help="Pick one push out of a directory holding several, e.g. "
             "--part-prefix Video-MME-v2",
    )
    pull_parser.add_argument(
        "--part-suffix",
        metavar="<ext>",
        default=None,
        help="Only needed to disambiguate a directory holding several "
             "pushes; the suffix is otherwise read off the part names",
    )
    pull_parser.set_defaults(func=cmd_pull)

    return parser


def main() -> None:
    parser = build_parser()
    args = parser.parse_args()
    args.func(args)


if __name__ == "__main__":
    main()
